/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica.pkg1;

/**
 *
 * @author Miguel Sánchez
 */
public class ColaFrame extends java.awt.Frame {

    /**
     * Creates new form ColaFrame
     */
    public ColaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     * @throws java.lang.InterruptedException
     */
    public static void main(String args[]) throws InterruptedException{
        int ancho = 500, alto = 700;
        int capacidad = 10;
        
        CanvasCola cv = new CanvasCola(capacidad);
        ColaFrame f = new ColaFrame();
        ColaLenta c = new ColaLenta(10, cv);
        
        Productor p1 = new Productor(c);
        Productor p2 = new Productor(c);
        Productor p3 = new Productor(c);
        Productor p4 = new Productor(c);
        
        Consumidor cn1 = new Consumidor(c);
        
        f.add(cv);
        f.setSize(alto, ancho);
        f.setTitle("Practica 3. Miguel Á. Sánchez - Cola Circular.");
        f.setLocationRelativeTo(null);
        f.setResizable(false);
        f.setVisible(true);       
        
        Thread t1 = new Thread(cn1);
        
        
        
        p1.start();
        p2.start();
        p3.start();
        p4.start();
        t1.start();
                
        t1.join();
        p1.interrupt();
        p2.interrupt();
        p3.interrupt();
        p4.interrupt();
        p1.join();
        p2.join();
        p3.join();
        p4.join();
       
        Thread.sleep(3000);
        System.exit(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
