//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica4_Cliente.ServiceGAlmacenesClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TDatosAlmacen", Namespace="http://schemas.datacontract.org/2004/07/Practica4_Servicio")]
    [System.SerializableAttribute()]
    public partial class TDatosAlmacen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FicheroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fichero {
            get {
                return this.FicheroField;
            }
            set {
                if ((object.ReferenceEquals(this.FicheroField, value) != true)) {
                    this.FicheroField = value;
                    this.RaisePropertyChanged("Fichero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TProducto", Namespace="http://schemas.datacontract.org/2004/07/Practica4_Servicio")]
    [System.SerializableAttribute()]
    public partial class TProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Practica4_Cliente.ServiceGAlmacenesClient.TFecha CaducidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodProdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Practica4_Cliente.ServiceGAlmacenesClient.TFecha Caducidad {
            get {
                return this.CaducidadField;
            }
            set {
                if ((object.ReferenceEquals(this.CaducidadField, value) != true)) {
                    this.CaducidadField = value;
                    this.RaisePropertyChanged("Caducidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodProd {
            get {
                return this.CodProdField;
            }
            set {
                if ((object.ReferenceEquals(this.CodProdField, value) != true)) {
                    this.CodProdField = value;
                    this.RaisePropertyChanged("CodProd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TFecha", Namespace="http://schemas.datacontract.org/2004/07/Practica4_Servicio")]
    [System.SerializableAttribute()]
    public partial class TFecha : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnyoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Anyo {
            get {
                return this.AnyoField;
            }
            set {
                if ((this.AnyoField.Equals(value) != true)) {
                    this.AnyoField = value;
                    this.RaisePropertyChanged("Anyo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Dia {
            get {
                return this.DiaField;
            }
            set {
                if ((this.DiaField.Equals(value) != true)) {
                    this.DiaField = value;
                    this.RaisePropertyChanged("Dia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mes {
            get {
                return this.MesField;
            }
            set {
                if ((this.MesField.Equals(value) != true)) {
                    this.MesField = value;
                    this.RaisePropertyChanged("Mes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceGAlmacenes.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DatosAlmacen", ReplyAction="http://tempuri.org/IServicio/DatosAlmacenResponse")]
        Practica4_Cliente.ServiceGAlmacenesClient.TDatosAlmacen DatosAlmacen(int pAlmacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DatosAlmacen", ReplyAction="http://tempuri.org/IServicio/DatosAlmacenResponse")]
        System.Threading.Tasks.Task<Practica4_Cliente.ServiceGAlmacenesClient.TDatosAlmacen> DatosAlmacenAsync(int pAlmacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/NProductos", ReplyAction="http://tempuri.org/IServicio/NProductosResponse")]
        int NProductos(int pAlmacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/NProductos", ReplyAction="http://tempuri.org/IServicio/NProductosResponse")]
        System.Threading.Tasks.Task<int> NProductosAsync(int pAlmacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CrearAlmacen", ReplyAction="http://tempuri.org/IServicio/CrearAlmacenResponse")]
        int CrearAlmacen(string pNombre, string pDireccion, string pNomFichero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CrearAlmacen", ReplyAction="http://tempuri.org/IServicio/CrearAlmacenResponse")]
        System.Threading.Tasks.Task<int> CrearAlmacenAsync(string pNombre, string pDireccion, string pNomFichero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AbrirAlmacen", ReplyAction="http://tempuri.org/IServicio/AbrirAlmacenResponse")]
        int AbrirAlmacen(string pNomFichero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AbrirAlmacen", ReplyAction="http://tempuri.org/IServicio/AbrirAlmacenResponse")]
        System.Threading.Tasks.Task<int> AbrirAlmacenAsync(string pNomFichero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GuardarAlmacen", ReplyAction="http://tempuri.org/IServicio/GuardarAlmacenResponse")]
        bool GuardarAlmacen(int pAlmacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/GuardarAlmacen", ReplyAction="http://tempuri.org/IServicio/GuardarAlmacenResponse")]
        System.Threading.Tasks.Task<bool> GuardarAlmacenAsync(int pAlmacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CerrarAlmacen", ReplyAction="http://tempuri.org/IServicio/CerrarAlmacenResponse")]
        bool CerrarAlmacen(int pAlmacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CerrarAlmacen", ReplyAction="http://tempuri.org/IServicio/CerrarAlmacenResponse")]
        System.Threading.Tasks.Task<bool> CerrarAlmacenAsync(int pAlmacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AlmacenAbierto", ReplyAction="http://tempuri.org/IServicio/AlmacenAbiertoResponse")]
        bool AlmacenAbierto(int pAlmacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AlmacenAbierto", ReplyAction="http://tempuri.org/IServicio/AlmacenAbiertoResponse")]
        System.Threading.Tasks.Task<bool> AlmacenAbiertoAsync(int pAlmacen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscaProducto", ReplyAction="http://tempuri.org/IServicio/BuscaProductoResponse")]
        int BuscaProducto(int pAlmacen, string pCodProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/BuscaProducto", ReplyAction="http://tempuri.org/IServicio/BuscaProductoResponse")]
        System.Threading.Tasks.Task<int> BuscaProductoAsync(int pAlmacen, string pCodProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerProducto", ReplyAction="http://tempuri.org/IServicio/ObtenerProductoResponse")]
        Practica4_Cliente.ServiceGAlmacenesClient.TProducto ObtenerProducto(int pAlmacen, int pPosProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerProducto", ReplyAction="http://tempuri.org/IServicio/ObtenerProductoResponse")]
        System.Threading.Tasks.Task<Practica4_Cliente.ServiceGAlmacenesClient.TProducto> ObtenerProductoAsync(int pAlmacen, int pPosProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AnadirProducto", ReplyAction="http://tempuri.org/IServicio/AnadirProductoResponse")]
        bool AnadirProducto(int pAlmacen, Practica4_Cliente.ServiceGAlmacenesClient.TProducto pProdNuevo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AnadirProducto", ReplyAction="http://tempuri.org/IServicio/AnadirProductoResponse")]
        System.Threading.Tasks.Task<bool> AnadirProductoAsync(int pAlmacen, Practica4_Cliente.ServiceGAlmacenesClient.TProducto pProdNuevo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ActualizarProducto", ReplyAction="http://tempuri.org/IServicio/ActualizarProductoResponse")]
        bool ActualizarProducto(int pAlmacen, Practica4_Cliente.ServiceGAlmacenesClient.TProducto pProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ActualizarProducto", ReplyAction="http://tempuri.org/IServicio/ActualizarProductoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarProductoAsync(int pAlmacen, Practica4_Cliente.ServiceGAlmacenesClient.TProducto pProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EliminarProducto", ReplyAction="http://tempuri.org/IServicio/EliminarProductoResponse")]
        bool EliminarProducto(int pAlmacen, string pCodProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EliminarProducto", ReplyAction="http://tempuri.org/IServicio/EliminarProductoResponse")]
        System.Threading.Tasks.Task<bool> EliminarProductoAsync(int pAlmacen, string pCodProducto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : Practica4_Cliente.ServiceGAlmacenesClient.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<Practica4_Cliente.ServiceGAlmacenesClient.IServicio>, Practica4_Cliente.ServiceGAlmacenesClient.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Practica4_Cliente.ServiceGAlmacenesClient.TDatosAlmacen DatosAlmacen(int pAlmacen) {
            return base.Channel.DatosAlmacen(pAlmacen);
        }
        
        public System.Threading.Tasks.Task<Practica4_Cliente.ServiceGAlmacenesClient.TDatosAlmacen> DatosAlmacenAsync(int pAlmacen) {
            return base.Channel.DatosAlmacenAsync(pAlmacen);
        }
        
        public int NProductos(int pAlmacen) {
            return base.Channel.NProductos(pAlmacen);
        }
        
        public System.Threading.Tasks.Task<int> NProductosAsync(int pAlmacen) {
            return base.Channel.NProductosAsync(pAlmacen);
        }
        
        public int CrearAlmacen(string pNombre, string pDireccion, string pNomFichero) {
            return base.Channel.CrearAlmacen(pNombre, pDireccion, pNomFichero);
        }
        
        public System.Threading.Tasks.Task<int> CrearAlmacenAsync(string pNombre, string pDireccion, string pNomFichero) {
            return base.Channel.CrearAlmacenAsync(pNombre, pDireccion, pNomFichero);
        }
        
        public int AbrirAlmacen(string pNomFichero) {
            return base.Channel.AbrirAlmacen(pNomFichero);
        }
        
        public System.Threading.Tasks.Task<int> AbrirAlmacenAsync(string pNomFichero) {
            return base.Channel.AbrirAlmacenAsync(pNomFichero);
        }
        
        public bool GuardarAlmacen(int pAlmacen) {
            return base.Channel.GuardarAlmacen(pAlmacen);
        }
        
        public System.Threading.Tasks.Task<bool> GuardarAlmacenAsync(int pAlmacen) {
            return base.Channel.GuardarAlmacenAsync(pAlmacen);
        }
        
        public bool CerrarAlmacen(int pAlmacen) {
            return base.Channel.CerrarAlmacen(pAlmacen);
        }
        
        public System.Threading.Tasks.Task<bool> CerrarAlmacenAsync(int pAlmacen) {
            return base.Channel.CerrarAlmacenAsync(pAlmacen);
        }
        
        public bool AlmacenAbierto(int pAlmacen) {
            return base.Channel.AlmacenAbierto(pAlmacen);
        }
        
        public System.Threading.Tasks.Task<bool> AlmacenAbiertoAsync(int pAlmacen) {
            return base.Channel.AlmacenAbiertoAsync(pAlmacen);
        }
        
        public int BuscaProducto(int pAlmacen, string pCodProducto) {
            return base.Channel.BuscaProducto(pAlmacen, pCodProducto);
        }
        
        public System.Threading.Tasks.Task<int> BuscaProductoAsync(int pAlmacen, string pCodProducto) {
            return base.Channel.BuscaProductoAsync(pAlmacen, pCodProducto);
        }
        
        public Practica4_Cliente.ServiceGAlmacenesClient.TProducto ObtenerProducto(int pAlmacen, int pPosProducto) {
            return base.Channel.ObtenerProducto(pAlmacen, pPosProducto);
        }
        
        public System.Threading.Tasks.Task<Practica4_Cliente.ServiceGAlmacenesClient.TProducto> ObtenerProductoAsync(int pAlmacen, int pPosProducto) {
            return base.Channel.ObtenerProductoAsync(pAlmacen, pPosProducto);
        }
        
        public bool AnadirProducto(int pAlmacen, Practica4_Cliente.ServiceGAlmacenesClient.TProducto pProdNuevo) {
            return base.Channel.AnadirProducto(pAlmacen, pProdNuevo);
        }
        
        public System.Threading.Tasks.Task<bool> AnadirProductoAsync(int pAlmacen, Practica4_Cliente.ServiceGAlmacenesClient.TProducto pProdNuevo) {
            return base.Channel.AnadirProductoAsync(pAlmacen, pProdNuevo);
        }
        
        public bool ActualizarProducto(int pAlmacen, Practica4_Cliente.ServiceGAlmacenesClient.TProducto pProducto) {
            return base.Channel.ActualizarProducto(pAlmacen, pProducto);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarProductoAsync(int pAlmacen, Practica4_Cliente.ServiceGAlmacenesClient.TProducto pProducto) {
            return base.Channel.ActualizarProductoAsync(pAlmacen, pProducto);
        }
        
        public bool EliminarProducto(int pAlmacen, string pCodProducto) {
            return base.Channel.EliminarProducto(pAlmacen, pCodProducto);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProductoAsync(int pAlmacen, string pCodProducto) {
            return base.Channel.EliminarProductoAsync(pAlmacen, pCodProducto);
        }
    }
}
