/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Persistencia.colabora;
import Persistencia.conexionOracle;
import Persistencia.experto;
import Persistencia.manejaColabora;
import Persistencia.manejaExperto;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel Sánchez
 */
public class VentanaColaboracionesPorCaso extends javax.swing.JFrame {
    
    DefaultTableModel modeloColaboracionPorCaso = new DefaultTableModel();
    conexionOracle co;
    manejaExperto mexperto;

    /**
     * Creates new form VentanaColaboracionesPorCaso
     */
    public VentanaColaboracionesPorCaso(conexionOracle co) {
        initComponents();
        jTableColaboracionPorCaso.setModel(modeloColaboracionPorCaso);
        String[] columnas = {"Código", "Nombre", "Especialidad", "Colaboración"};
        modeloColaboracionPorCaso.setColumnIdentifiers(columnas);
        jTableColaboracionPorCaso.getTableHeader().setResizingAllowed(false);
        jTableColaboracionPorCaso.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTableColaboracionPorCaso.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableColaboracionPorCaso.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableColaboracionPorCaso.getColumnModel().getColumn(3).setPreferredWidth(100);
        this.co = co;
        mexperto = new manejaExperto(co);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableColaboracionPorCaso = new javax.swing.JTable();
        label1 = new java.awt.Label();
        jButtonMostrar = new javax.swing.JButton();
        jTextIntroduceCodigoCaso = new javax.swing.JTextField();
        jButtonordenarporexperto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableColaboracionPorCaso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableColaboracionPorCaso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTableColaboracionPorCaso);

        label1.setText("Introduce el Código de un Caso");

        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        jTextIntroduceCodigoCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIntroduceCodigoCasoActionPerformed(evt);
            }
        });

        jButtonordenarporexperto.setText("Todas ordenadas por Experto");
        jButtonordenarporexperto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonordenarporexpertoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextIntroduceCodigoCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonMostrar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonordenarporexperto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonMostrar)
                        .addComponent(jTextIntroduceCodigoCaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonordenarporexperto)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        // TODO add your handling code here:
        manejaColabora mc = new manejaColabora(co);
        try {
            ResultSet rs = mc.listaColaboradoresPorCaso(jTextIntroduceCodigoCaso.getText());
            while (modeloColaboracionPorCaso.getRowCount() > 0) {//te da el numero de filas que hay en la tabla
                modeloColaboracionPorCaso.removeRow(0); //Elimina la fila siempre que haya alguna
            }
            while(rs.next() == true){
                String[] fila = new String[4];
                fila[0] = rs.getNString("CODEXPERTO");
                fila[1] = rs.getNString("NOMBRE_EXPERTO");
                fila[2] = rs.getNString("ESPECIALIDAD");
                fila[3] = rs.getNString("DESCRIPCION_COLABORACION");
                modeloColaboracionPorCaso.addRow(fila);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al obtener la lista de colaboraciones por caso.");
        }
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void jTextIntroduceCodigoCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIntroduceCodigoCasoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIntroduceCodigoCasoActionPerformed

    public void ordenarcolaexpertos(){
    try {
            // TODO add your handling code here:
            
            ArrayList<experto> e = mexperto.listaExpertosordenadas();
            while (modeloColaboracionPorCaso.getRowCount() > 0) {//te da el numero de filas
                modeloColaboracionPorCaso.removeRow(0); //Elimina la fila
            }
            for (int i = 0; i < e.size(); i++) {
                String[] fila = {e.get(i).getCodExperto(), e.get(i).getNombre(), e.get(i).getEspecialidad(), e.get(i).getSexo()};
                
                modeloColaboracionPorCaso.addRow(fila); //Agrega una fila
            }
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(null, "Error al ordenar toda la lista.");
        }
    }
    
    private void jButtonordenarporexpertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonordenarporexpertoActionPerformed
        // TODO add your handling code here:
        ordenarcolaexpertos();
    }//GEN-LAST:event_jButtonordenarporexpertoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JButton jButtonordenarporexperto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableColaboracionPorCaso;
    private javax.swing.JTextField jTextIntroduceCodigoCaso;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
