/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Persistencia.colabora;
import Persistencia.conexionOracle;
import Persistencia.experto;
import Persistencia.manejaColabora;
import Persistencia.manejaExperto;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel Sánchez
 */
public class VentanaColaboraciones extends javax.swing.JFrame {

    DefaultTableModel modeloColaboracion = new DefaultTableModel(); //Para agregar elementos y quitarlos se usa el modeloExpertos
    conexionOracle co;

    /**
     * Creates new form NewJFrame
     */
    public VentanaColaboraciones(conexionOracle co) {
        initComponents();
        jTableColaboraciones.setModel(modeloColaboracion);
        String[] columna = {"Descripción de Colaboración"};
        modeloColaboracion.setColumnIdentifiers(columna);
        jTableColaboraciones.getTableHeader().setResizingAllowed(false);
        jTableColaboraciones.getColumnModel().getColumn(0).setPreferredWidth(25);
        this.co = co;
        manejaExperto mexperto = new manejaExperto(co);
        try {
            ArrayList<experto> ex = mexperto.listaExpertos();
            for (int i = 0; i < ex.size(); i++) {
                jComboBoxexperto.addItem(ex.get(i));
            }
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(null, "Error al listar expertos.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        Experto = new java.awt.Label();
        jComboBoxexperto = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableColaboraciones = new javax.swing.JTable();
        Colaboraciones = new java.awt.Label();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Experto.setText("Experto");

        jComboBoxexperto.setModel(new javax.swing.DefaultComboBoxModel<>());
        jComboBoxexperto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxexpertoActionPerformed(evt);
            }
        });

        jTableColaboraciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane2.setViewportView(jTableColaboraciones);

        Colaboraciones.setText("Colaboraciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Experto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBoxexperto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Colaboraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Experto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Colaboraciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxexperto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Colaboraciones.getAccessibleContext().setAccessibleName("Colabor");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxexpertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxexpertoActionPerformed
        // TODO add your handling code here:
        manejaColabora mc = new manejaColabora(co);
        while (modeloColaboracion.getRowCount() > 0) {//te da el numero de filas que hay en la tabla
            modeloColaboracion.removeRow(0); //Elimina la fila siempre que haya alguna
        }
        experto ex = (experto) jComboBoxexperto.getSelectedItem();//Nos da el objeto que esta seleccionado en el combobox
        try {
            ArrayList<colabora> cl = mc.colaboraciones(ex.getCodExperto());
            if (cl.isEmpty() == false) { //True si esta vacio, falso si hay contenido
                for (colabora c : cl) {
                    String[] fila = new String[1];
                    fila[0] = c.getDescripcionColaboracion();
                    modeloColaboracion.addRow(fila);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Este experto no participa en ninguna colabaricon.");
            }
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(null, "Error al obtener la lista en el combobox.");
        }
    }//GEN-LAST:event_jComboBoxexpertoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaColaboraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaColaboraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaColaboraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaColaboraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Colaboraciones;
    private java.awt.Label Experto;
    private javax.swing.JComboBox<experto> jComboBoxexperto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableColaboraciones;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
