/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Persistencia.conexionOracle;
import Persistencia.experto;
import Persistencia.manejaExperto;
import java.sql.Array;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.graalvm.compiler.nodes.NodeView;
import sun.jvm.hotspot.utilities.soql.SOQLException;

/**
 *
 * @author Miguel Sánchez
 */
public class VentanaExpertos extends javax.swing.JFrame {

    DefaultTableModel modeloExpertos = new DefaultTableModel(); //Para agregar elementos y quitarlos se usa el modeloExpertos
    conexionOracle co;

    /**
     * Creates new form VentanaExpertos
     *
     * @param co
     */
    public VentanaExpertos(conexionOracle co) {
        initComponents();
        jTable1Expertos.setModel(modeloExpertos);
        String[] columnasTabla = {"Codigo", "Nombre", "Pais", "Sexo", "Especialidad"};//Para poner nombres a las columnas
        modeloExpertos.setColumnIdentifiers(columnasTabla); //Aplicamos esos nombres con el setComulm_Identifiers

        jTable1Expertos.getTableHeader().setResizingAllowed(false);//Para que las columnas no se redimensiones
        jTable1Expertos.getColumnModel().getColumn(0).setPreferredWidth(10);//Para cambiar el tamaño de las columnas
        jTable1Expertos.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable1Expertos.getColumnModel().getColumn(2).setPreferredWidth(10);
        jTable1Expertos.getColumnModel().getColumn(3).setPreferredWidth(10);
        jTable1Expertos.getColumnModel().getColumn(4).setPreferredWidth(100);
        this.co = co;
        try {
            // TODO add your handling code here:
            manejaExperto m = new manejaExperto(co);
            ArrayList<experto> ex = m.listaExpertos();
            while (modeloExpertos.getRowCount() > 0) {//te da el numero de filas
                modeloExpertos.removeRow(0); //Elimina la fila
            }
            for (int i = 0; i < ex.size(); i++) {
                String[] fila = new String[5];
                fila[0] = ex.get(i).getCodExperto();
                fila[1] = ex.get(i).getNombre();
                fila[2] = ex.get(i).getPais();
                fila[3] = ex.get(i).getSexo();
                fila[4] = ex.get(i).getEspecialidad();
                modeloExpertos.addRow(fila); //Agrega una fila
            }
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(null, "Error al listar todos en el constructor.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Expertos = new javax.swing.JTable();
        jButton1FiltraPorPaís = new javax.swing.JButton();
        jTextFieldIntroduce = new javax.swing.JTextField();
        jButton1ListarTodo = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jTextFieldgenero = new javax.swing.JTextField();
        jButtonContar = new javax.swing.JButton();
        jLabelResultadogeneros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1Expertos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1Expertos);

        jButton1FiltraPorPaís.setText("Filtrar por pais");
        jButton1FiltraPorPaís.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1FiltraPorPaísActionPerformed(evt);
            }
        });

        jTextFieldIntroduce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntroduceActionPerformed(evt);
            }
        });

        jButton1ListarTodo.setText("Listar todos");
        jButton1ListarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ListarTodoActionPerformed(evt);
            }
        });

        label1.setText("País");

        label2.setText("Sexo");

        jTextFieldgenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldgeneroActionPerformed(evt);
            }
        });

        jButtonContar.setText("Contar");
        jButtonContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldIntroduce, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1FiltraPorPaís, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1ListarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonContar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelResultadogeneros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1FiltraPorPaís)
                        .addComponent(jTextFieldIntroduce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1ListarTodo))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonContar)
                        .addComponent(jLabelResultadogeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1FiltraPorPaísActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1FiltraPorPaísActionPerformed
        try {
            // TODO add your handling code here:
            /*String vCodigo = jTextFieldIntroduce.getText();
            Object[] columna = new Object [1];
            columna[0] = vCodigo;
            modeloExpertos.addRow(columna);*/
            manejaExperto m = new manejaExperto(co);
            ArrayList<experto> ex = m.listaExpertosPorPais(jTextFieldIntroduce.getText()); //Me creo un array que me devuelva los expertos del pais que le indique
            while (modeloExpertos.getRowCount() > 0) {//te da el numero de filas que hay en la tabla
                modeloExpertos.removeRow(0); //Elimina la fila siempre que haya alguna
            }
            for (int i = 0; i < ex.size(); i++) {
                String[] fila = new String[5];
                fila[0] = ex.get(i).getCodExperto();
                fila[1] = ex.get(i).getNombre();
                fila[2] = ex.get(i).getPais();
                fila[3] = ex.get(i).getSexo();
                fila[4] = ex.get(i).getEspecialidad();
                modeloExpertos.addRow(fila); //Agrega una fila
            }
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(null,"Error al listar expertos.");
        }
    }//GEN-LAST:event_jButton1FiltraPorPaísActionPerformed

    private void jTextFieldIntroduceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntroduceActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldIntroduceActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ListarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ListarTodoActionPerformed
        try {
            // TODO add your handling code here:
            manejaExperto m = new manejaExperto(co);
            ArrayList<experto> ex = m.listaExpertos();
            while (modeloExpertos.getRowCount() > 0) {//te da el numero de filas
                modeloExpertos.removeRow(0); //Elimina la fila
            }
            for (int i = 0; i < ex.size(); i++) {
                String[] fila = new String[5];
                fila[0] = ex.get(i).getCodExperto();
                fila[1] = ex.get(i).getNombre();
                fila[2] = ex.get(i).getPais();
                fila[3] = ex.get(i).getSexo();
                fila[4] = ex.get(i).getEspecialidad();
                modeloExpertos.addRow(fila); //Agrega una fila
            }
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(null, "Error al listar todos.");
        }
    }//GEN-LAST:event_jButton1ListarTodoActionPerformed

    private void jTextFieldgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldgeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldgeneroActionPerformed

    private void jButtonContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContarActionPerformed
        // TODO add your handling code here:
        manejaExperto me = new manejaExperto(co);
        String genero = jTextFieldgenero.getText().trim();//Obtenemos el texto introducido y con el .trim Eliminar los espacios
        try {
            int numero = me.sexoExperto(genero);
            if (genero.equals("M")) {
                jLabelResultadogeneros.setText("Hay " + numero + " hombres en la base de datos");
            } else {
                jLabelResultadogeneros.setText("Hay " + numero + " mujeres en la base de datos");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al obtener el sexo del experto.");
        }
    }//GEN-LAST:event_jButtonContarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaExpertos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaExpertos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaExpertos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaExpertos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaExpertos(co).setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1FiltraPorPaís;
    private javax.swing.JButton jButton1ListarTodo;
    private javax.swing.JButton jButtonContar;
    private javax.swing.JLabel jLabelResultadogeneros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1Expertos;
    private javax.swing.JTextField jTextFieldIntroduce;
    private javax.swing.JTextField jTextFieldgenero;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables

}
