/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorAlmacenes.h"


void supermercado_1(char *host) {
	CLIENT *clnt;
	TDatosAlmacen  *result_1;
	int  datosalmacen_1_arg;
	int  *result_2;
	int  nproductos_1_arg;
	int  *result_3;
	TDatosAlmacen  crearalmacen_1_arg;
	int  *result_4;
	char  abriralmacen_1_arg;
	bool_t  *result_5;
	int  guardaralmacen_1_arg;
	bool_t  *result_6;
	int  cerraralmacen_1_arg;
	bool_t  *result_7;
	int  almacenabierto_1_arg;
	int  *result_8;
	TBusProd  buscaproducto_1_arg;
	TProducto  *result_9;
	TObtProd  obtenerproducto_1_arg;
	bool_t  *result_10;
	TActProd  anadirproducto_1_arg;
	bool_t  *result_11;
	TActProd  actualizarproducto_1_arg;
	bool_t  *result_12;
	TBusProd  eliminarproducto_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SUPERMERCADO, SUPERMERCADO_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = datosalmacen_1(&datosalmacen_1_arg, clnt);
	if (result_1 == (TDatosAlmacen *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = nproductos_1(&nproductos_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = crearalmacen_1(&crearalmacen_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = abriralmacen_1(&abriralmacen_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = guardaralmacen_1(&guardaralmacen_1_arg, clnt);
	if (result_5 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = cerraralmacen_1(&cerraralmacen_1_arg, clnt);
	if (result_6 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = almacenabierto_1(&almacenabierto_1_arg, clnt);
	if (result_7 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = buscaproducto_1(&buscaproducto_1_arg, clnt);
	if (result_8 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = obtenerproducto_1(&obtenerproducto_1_arg, clnt);
	if (result_9 == (TProducto *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = anadirproducto_1(&anadirproducto_1_arg, clnt);
	if (result_10 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = actualizarproducto_1(&actualizarproducto_1_arg, clnt);
	if (result_11 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = eliminarproducto_1(&eliminarproducto_1_arg, clnt);
	if (result_12 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

Cadena NomAlmacen;

int menu(){
	int opcion;
	printf("----- Menú Almacenes ----- %s\n\n",NomAlmacen);
	printf("1.- Crear un almacén vacío.\n");
	printf("2.- Abrir un fichero de almacén.\n");
	printf("3.- Cerrar un almacen.\n");
	printf("4.- Guardar Datos.\n");
	printf("5.- Listar productos del almacén.\n");
	printf("6.- Añadir un producto.\n");
	printf("7.- Actualizar un producto.\n");
	printf("8.- Consultar un producto.\n");
	printf("9.- Eliminar un producto.\n");
	printf("0.- Salir.\n");
	printf("Elige una opcion: "); 
	scanf("%d",&opcion);
	return opcion;
}



int main (int argc, char *argv[]) {
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	CLIENT *clnt = clnt_create (host, SUPERMERCADO, SUPERMERCADO_VER, "tcp");
	if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
	strcpy(NomAlmacen,"Ninguno.");
	int almacenabierto = -1;

	int opcionmenu = -1;
	while (opcionmenu != 0) {
		opcionmenu = menu();

		switch (opcionmenu) {
		case 1: 
				if(almacenabierto != -1){
					cerraralmacen_1(&almacenabierto, clnt);
				}
				struct TDatosAlmacen tdatosmenu;
				printf("Nombre del Almacen:\n"); 
				scanf("%s", tdatosmenu.Nombre);
				printf("Direccion del Almacen:\n");
				scanf("%s", tdatosmenu.Direccion);
				printf("Nombre del fichero:\n");
				scanf("%s",tdatosmenu.Fichero);
				int  *result_3;
				result_3 = crearalmacen_1(&tdatosmenu, clnt);
				if(*result_3 == -1){
					printf("No se ha podido abrir el almacen.\n");
					strcpy(NomAlmacen,"Ninguno.");
				} else {
					printf("Almacen abierto corrrectamente.\n");
					strcpy(NomAlmacen,tdatosmenu.Nombre);
				}
				almacenabierto = *result_3;
			break;
		case 2:
				if(almacenabierto != -1){
					cerraralmacen_1(&almacenabierto, clnt);
				}
				Cadena Nomf;
				printf("Introduce nombre del fichero previamente creado:");
				scanf("%s", Nomf);
				int *result_4 = abriralmacen_1(Nomf, clnt);
				printf("Result_4: %d", *result_4);
				if(*result_4 != -1){
					struct TDatosAlmacen tdatosmenu;
					tdatosmenu = *datosalmacen_1(result_4, clnt);
					strcpy(NomAlmacen,tdatosmenu.Nombre);
					printf("Almacen abierto correctamente.\n");
				} else {
					printf("El fichero del almacen no ha sido encontrado.\n");
					strcpy(NomAlmacen,"Ninguno.");
				}
				almacenabierto = *result_4;
			break;
		case 3: 
				if(almacenabierto != -1){
					bool_t *result_6 = cerraralmacen_1(&almacenabierto, clnt);
					if(*result_6 == TRUE){
						printf("Almacen cerrado.\n");
						strcpy(NomAlmacen,"Ninguno.");
						almacenabierto = -1;
					} else {
						printf("No se ha encontrado el almacen a cerrar.\n");
					}
				} else {
					printf("No se ha encontrado ningun almacen abierto.\n");
				}
			break;
		case 4:
				if(almacenabierto != -1){
					bool_t *result_5 = guardaralmacen_1(&almacenabierto, clnt);
					if(*result_5 == TRUE){
						printf("Los datos del almacen han sido guardados.\n");
					} else {
						printf("No se ha podido cerrar el almacen.\n");
					}
				} else {
					printf("No se ha encontrado ningun almacen abierto.\n");
				}
			break;
		case 5: ;
				TProducto *tprodd;
				TObtProd tobprod;
				if (almacenabierto != -1){
					int *result_2 = nproductos_1(&almacenabierto, clnt);
					if(*result_2 == 0){
						printf("El almacen no tiene productos.\n");
					} else {
						printf("************************************************************************************\n");
						printf("CODIGO  NOMBRE                         PRECIO    CANTIDAD    FECHA CADUCIDAD\n");
						tobprod.Almacen = almacenabierto;
						for (int i = 0; i < *result_2; i++){
							tobprod.PosProducto = i;
							tprodd = obtenerproducto_1(&tobprod, clnt);
							printf("%-7s %-30s %-5.2f %5d           %d/%d/%d\n",tprodd->CodProd,tprodd->NombreProd,tprodd->Precio,tprodd->Cantidad,tprodd->Caducidad.Dia,tprodd->Caducidad.Mes,tprodd->Caducidad.Anyo);
						} 
					}
				} else {
					printf("No se ha encontrado ningun almacen abierto.\n");
				}
		
			break;
		case 6:
				if(almacenabierto != -1){
					TActProd tprod;
					tprod.Almacen = almacenabierto;
					printf("Intoduzca el codigo del producto:\n");
					scanf("%s",tprod.Producto.CodProd);
					printf("Introduzca la cantidad del producto:\n");
					scanf("%d",&tprod.Producto.Cantidad);
					printf("Introduzca el nombre del producto:\n");
					scanf("%s",tprod.Producto.NombreProd);
					printf("Introduzca el precio del producto:\n");
					scanf("%f",&tprod.Producto.Precio);
					printf("Introduzca una descripcion del producto:\n");
					scanf("%s",tprod.Producto.Descripcion);
					printf("Introduzca la Fecha de caducidad: ");
					scanf("%d/%d/%d",&tprod.Producto.Caducidad.Dia, &tprod.Producto.Caducidad.Mes, &tprod.Producto.Caducidad.Anyo);
					bool_t *result_10 = anadirproducto_1(&tprod, clnt);
					if(*result_10 == TRUE){
						printf("El producto se ha introducido correctamente.\n");
					} else{
						printf("El producto ya existe en este almacen.\n");
					}
				} else {
					printf("No se ha encontrado ningun almacen abierto.\n");
				}
			break;
		case 7: ;
				TActProd tprod;
				TBusProd tbprod;
				TProducto *tproducto;
				TObtProd tobtprod;
				Cadena respuesta;
				if(almacenabierto != -1){
					printf("Introduce el codigo del producto a actualizar:\n");
					scanf("%s",tbprod.CodProducto);
					tbprod.Almacen = almacenabierto;
					int *result_8 = buscaproducto_1(&tbprod, clnt);
					if(*result_8 != -1){
						tobtprod.Almacen = almacenabierto;
						tobtprod.PosProducto = *result_8;
						tproducto = obtenerproducto_1(&tobtprod, clnt);
						tprod.Almacen = almacenabierto;
						printf("El producto ha sido encontrado.\n");
						strcpy(tprod.Producto.CodProd,tproducto->CodProd);
						tprod.Producto.Cantidad = tproducto->Cantidad;
						printf("¿Desea actualizar la cantidad del producto? Si/No\n");
						scanf("%s",respuesta);
						if(strcmp("Si",respuesta) == 0) {
							printf("Introduce la nueva cantidad del producto:\n");
							scanf("%d",&tprod.Producto.Cantidad);
						}
						printf("¿Desea actualizar el nombre del producto? Si/No\n");
						scanf("%s",respuesta);
						strcpy(tprod.Producto.NombreProd,tproducto->NombreProd);
						if(strcmp("Si",respuesta) == 0) {
							printf("Introduce el nuevo nombre del producto:\n");
							scanf("%s",tprod.Producto.NombreProd);
						}
						tprod.Producto.Precio = tproducto->Precio;
						printf("¿Desea actualizar el precio del producto? Si/No\n");
						scanf("%s",respuesta);
						if(strcmp("Si",respuesta) == 0) {
							printf("Introduce el nuevo precio del producto:\n");
							scanf("%f",&tprod.Producto.Precio);
						}
						printf("¿Desea actualizar la descripcion del producto? Si/No\n");
						scanf("%s",respuesta);
						strcpy(tprod.Producto.Descripcion,tproducto->Descripcion);
						if(strcmp("Si",respuesta) == 0) {
							printf("Introduce la nueva descripcion del producto:\n");
							scanf("%s",tprod.Producto.Descripcion);
						}
						tprod.Producto.Caducidad = tproducto->Caducidad;
						printf("¿Desea actualizar la caducidad del producto? Si/No\n");
						scanf("%s",respuesta);
						if(strcmp("Si",respuesta) == 0) {
							printf("Introduce la nueva caducidad del producto en formato dd/mm/aaaa:\n");
							scanf("%d/%d/%d",&tprod.Producto.Caducidad.Dia, &tprod.Producto.Caducidad.Mes, &tprod.Producto.Caducidad.Anyo);
						}
						bool_t *result_11 = actualizarproducto_1(&tprod, clnt);
						if(*result_11 == TRUE){
							printf("El producto ha sido actualizado correctamente.\n");
						} else {
							printf("El producto no ha podido ser actualizado.\n");
						}
					} else {
						printf("El producto no se encuentra en el almacen.\n");
					}
				} else{
					printf("No hay ningun almacen abierto.\n");
				}
			break;
		case 8: ;
			TBusProd tbbprod;
			TProducto *ttproducto;
			TObtProd tobtprodd;
			if(almacenabierto != -1){
				tbbprod.Almacen = almacenabierto;
				printf("Introduce el codigo del producto a mostrar:");
				scanf("%s", tbbprod.CodProducto);
				int *result_8 = buscaproducto_1(&tbbprod, clnt);
				if(*result_8 != -1){
					tobtprodd.Almacen = almacenabierto;
					tobtprodd.PosProducto = *result_8;
					ttproducto = obtenerproducto_1(&tobtprodd, clnt);
					printf("Codigo: %s , Cantidad: %d , Producto: %s , Precio: %f , Descripcion: %s , Fecha Caducidad: %d/%d/%d \n",ttproducto->CodProd, ttproducto->Cantidad, ttproducto->NombreProd, ttproducto->Precio, ttproducto->Descripcion, ttproducto->Caducidad.Dia, ttproducto->Caducidad.Mes, ttproducto->Caducidad.Anyo);
				} else {
					printf("No se ha encontrado ningun producto con ese codigo.\n");
				}
			} else{
				printf("No hay ningun almacen abierto.\n");
			}
			break;
		case 9: ;
			TBusProd tbprood;
			if(almacenabierto != -1) {
				tbprood.Almacen = almacenabierto;
				printf("Introduce el codigo del producto a eliminar:");
				scanf("%s", tbprood.CodProducto);
				int *result_8 = buscaproducto_1(&tbprood, clnt);
				if(*result_8 != -1){
					bool_t *result_12 = eliminarproducto_1(&tbprood, clnt);
					if(*result_12 == TRUE){
						printf("El producto ha sido eliminado correctamente.\n");
					} else {
						printf("El producto no ha sido eliminado correctamente.\n");
					}
				} else {
					printf("No se ha encontrado el producto.\n");
				}
			} else {
				printf("No hay ningun almacen abierto.\n");
			}
			break;
		}
	}
	printf("\n*** HASTA PRONTO ***");

exit (0);
}
